In [2]:
import pandas as pd
import numpy as np

In [3]:

df = pd.read_csv("../data/raw/Matches.csv")

#df = pd.read_csv('data/raw/Matches.csv')

C:\Users\jjgoe\AppData\Local\Temp\ipykernel_29360\1081406840.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/Matches.csv")

In [4]:
df.head()

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
0,F1,2000-07-28,NaN,Marseille,Troyes,1686.34,1586.57,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,2000-07-28,NaN,Paris SG,Strasbourg,1714.89,1642.51,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F2,2000-07-28,NaN,Wasquehal,Nancy,1465.08,1633.80,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,2000-07-29,NaN,Auxerre,Sedan,1635.58,1624.22,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,2000-07-29,NaN,Bordeaux,Metz,1734.34,1673.11,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2 = df[['Division', 'MatchDate', 'HomeTeam', 'AwayTeam', 'FTResult']]
df2.head()

  Division   MatchDate   HomeTeam    AwayTeam FTResult
0       F1  2000-07-28  Marseille      Troyes        H
1       F1  2000-07-28   Paris SG  Strasbourg        H
2       F2  2000-07-28  Wasquehal       Nancy        A
3       F1  2000-07-29    Auxerre       Sedan        A
4       F1  2000-07-29   Bordeaux        Metz        D

In [6]:
df2.shape

(230557, 5)

In [7]:
df3 = df2[(df2['Division'] == 'E0') | (df2['Division'] == 'SP1') | (df2['Division'] == 'D1')]

df3.head()

   Division   MatchDate        HomeTeam       AwayTeam FTResult
39       D1  2000-08-11        Dortmund  Hansa Rostock        H
42       D1  2000-08-12   Bayern Munich         Hertha        H
43       D1  2000-08-12        Freiburg      Stuttgart        H
44       D1  2000-08-12         Hamburg    Munich 1860        D
45       D1  2000-08-12  Kaiserslautern         Bochum        A

In [8]:
df3.shape

(25940, 5)

In [9]:
df4 = df3.copy()
df4.head()

   Division   MatchDate        HomeTeam       AwayTeam FTResult
39       D1  2000-08-11        Dortmund  Hansa Rostock        H
42       D1  2000-08-12   Bayern Munich         Hertha        H
43       D1  2000-08-12        Freiburg      Stuttgart        H
44       D1  2000-08-12         Hamburg    Munich 1860        D
45       D1  2000-08-12  Kaiserslautern         Bochum        A

In [10]:
df4['MatchDate'] = pd.to_datetime(df4['MatchDate'])
df4.head()

   Division  MatchDate        HomeTeam       AwayTeam FTResult
39       D1 2000-08-11        Dortmund  Hansa Rostock        H
42       D1 2000-08-12   Bayern Munich         Hertha        H
43       D1 2000-08-12        Freiburg      Stuttgart        H
44       D1 2000-08-12         Hamburg    Munich 1860        D
45       D1 2000-08-12  Kaiserslautern         Bochum        A

In [11]:
df4['Season'] = df4['Season'] = np.where(df4['MatchDate'].dt.month >=8,
                                        df4['MatchDate'].dt.year,
                                        df4['MatchDate'].dt.year -1)
df4

       Division  MatchDate        HomeTeam       AwayTeam FTResult  Season
39           D1 2000-08-11        Dortmund  Hansa Rostock        H    2000
42           D1 2000-08-12   Bayern Munich         Hertha        H    2000
43           D1 2000-08-12        Freiburg      Stuttgart        H    2000
44           D1 2000-08-12         Hamburg    Munich 1860        D    2000
45           D1 2000-08-12  Kaiserslautern         Bochum        A    2000
...         ...        ...             ...            ...      ...     ...
230507       E0 2025-05-25   Nott'm Forest        Chelsea        A    2024
230508       E0 2025-05-25     Southampton        Arsenal        A    2024
230509       E0 2025-05-25       Tottenham       Brighton        A    2024
230510       E0 2025-05-25          Wolves      Brentford        D    2024
230535      SP1 2025-05-25      Ath Bilbao      Barcelona        A    2024

[25940 rows x 6 columns]

In [12]:
home_df = df4[['Division', 'MatchDate', 'HomeTeam', 'FTResult', 'Season']]
home_df

       Division  MatchDate        HomeTeam FTResult  Season
39           D1 2000-08-11        Dortmund        H    2000
42           D1 2000-08-12   Bayern Munich        H    2000
43           D1 2000-08-12        Freiburg        H    2000
44           D1 2000-08-12         Hamburg        D    2000
45           D1 2000-08-12  Kaiserslautern        A    2000
...         ...        ...             ...      ...     ...
230507       E0 2025-05-25   Nott'm Forest        A    2024
230508       E0 2025-05-25     Southampton        A    2024
230509       E0 2025-05-25       Tottenham        A    2024
230510       E0 2025-05-25          Wolves        D    2024
230535      SP1 2025-05-25      Ath Bilbao        A    2024

[25940 rows x 5 columns]

In [13]:
def points(result):
    if result == 'H':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

In [14]:
home_df['Points'] = home_df['FTResult'].apply(points)

In [15]:
home_df

       Division  MatchDate        HomeTeam FTResult  Season  Points
39           D1 2000-08-11        Dortmund        H    2000       3
42           D1 2000-08-12   Bayern Munich        H    2000       3
43           D1 2000-08-12        Freiburg        H    2000       3
44           D1 2000-08-12         Hamburg        D    2000       1
45           D1 2000-08-12  Kaiserslautern        A    2000       0
...         ...        ...             ...      ...     ...     ...
230507       E0 2025-05-25   Nott'm Forest        A    2024       0
230508       E0 2025-05-25     Southampton        A    2024       0
230509       E0 2025-05-25       Tottenham        A    2024       0
230510       E0 2025-05-25          Wolves        D    2024       1
230535      SP1 2025-05-25      Ath Bilbao        A    2024       0

[25940 rows x 6 columns]

In [16]:
home_df['Team'] = home_df['HomeTeam']
home_df.head()

,Division,MatchDate,HomeTeam,FTResult,Season,Points,Team
39,D1,2000-08-11,Dortmund,H,2000,3,Dortmund
42,D1,2000-08-12,Bayern Munich,H,2000,3,Bayern Munich
43,D1,2000-08-12,Freiburg,H,2000,3,Freiburg
44,D1,2000-08-12,Hamburg,D,2000,1,Hamburg
45,D1,2000-08-12,Kaiserslautern,A,2000,0,Kaiserslautern

In [17]:
def away_points(result):
    if result == 'A':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

In [18]:
away_df = df4[['Division', 'MatchDate', 'AwayTeam', 'FTResult', 'Season']]
away_df

       Division  MatchDate       AwayTeam FTResult  Season
39           D1 2000-08-11  Hansa Rostock        H    2000
42           D1 2000-08-12         Hertha        H    2000
43           D1 2000-08-12      Stuttgart        H    2000
44           D1 2000-08-12    Munich 1860        D    2000
45           D1 2000-08-12         Bochum        A    2000
...         ...        ...            ...      ...     ...
230507       E0 2025-05-25        Chelsea        A    2024
230508       E0 2025-05-25        Arsenal        A    2024
230509       E0 2025-05-25       Brighton        A    2024
230510       E0 2025-05-25      Brentford        D    2024
230535      SP1 2025-05-25      Barcelona        A    2024

[25940 rows x 5 columns]

In [19]:
away_df['Points'] = away_df['FTResult'].apply(away_points)

In [20]:
away_df

       Division  MatchDate       AwayTeam FTResult  Season  Points
39           D1 2000-08-11  Hansa Rostock        H    2000       0
42           D1 2000-08-12         Hertha        H    2000       0
43           D1 2000-08-12      Stuttgart        H    2000       0
44           D1 2000-08-12    Munich 1860        D    2000       1
45           D1 2000-08-12         Bochum        A    2000       3
...         ...        ...            ...      ...     ...     ...
230507       E0 2025-05-25        Chelsea        A    2024       3
230508       E0 2025-05-25        Arsenal        A    2024       3
230509       E0 2025-05-25       Brighton        A    2024       3
230510       E0 2025-05-25      Brentford        D    2024       1
230535      SP1 2025-05-25      Barcelona        A    2024       3

[25940 rows x 6 columns]

In [21]:
away_df['Team'] = away_df['AwayTeam']
away_df.head()

   Division  MatchDate       AwayTeam FTResult  Season  Points           Team
39       D1 2000-08-11  Hansa Rostock        H    2000       0  Hansa Rostock
42       D1 2000-08-12         Hertha        H    2000       0         Hertha
43       D1 2000-08-12      Stuttgart        H    2000       0      Stuttgart
44       D1 2000-08-12    Munich 1860        D    2000       1    Munich 1860
45       D1 2000-08-12         Bochum        A    2000       3         Bochum

In [22]:
combined_df = pd.concat([home_df, away_df], ignore_index = True)
combined_df

,Division,MatchDate,HomeTeam,FTResult,Season,Points,Team,AwayTeam
0,D1,2000-08-11,Dortmund,H,2000,3,Dortmund,NaN
1,D1,2000-08-12,Bayern Munich,H,2000,3,Bayern Munich,NaN
2,D1,2000-08-12,Freiburg,H,2000,3,Freiburg,NaN
3,D1,2000-08-12,Hamburg,D,2000,1,Hamburg,NaN
4,D1,2000-08-12,Kaiserslautern,A,2000,0,Kaiserslautern,NaN
...,...,...,...,...,...,...,...,...
51875,E0,2025-05-25,NaN,A,2024,3,Chelsea,Chelsea
51876,E0,2025-05-25,NaN,A,2024,3,Arsenal,Arsenal
51877,E0,2025-05-25,NaN,A,2024,3,Brighton,Brighton
51878,E0,2025-05-25,NaN,D,2024,1,Brentford,Brentford
51879,SP1,2025-05-25,NaN,A,2024,3,Barcelona,Barcelona

In [23]:
combined_df = combined_df.sort_values(['Division', 'Team', 'Season', 'MatchDate'])
combined_df.head()

      Division  MatchDate HomeTeam FTResult  Season  Points    Team AwayTeam
32008       D1 2006-08-12      NaN        H    2006       0  Aachen   Aachen
6076        D1 2006-08-19   Aachen        A    2006       0  Aachen      NaN
32045       D1 2006-08-26      NaN        A    2006       3  Aachen   Aachen
6132        D1 2006-09-16   Aachen        H    2006       3  Aachen      NaN
32092       D1 2006-09-23      NaN        H    2006       0  Aachen   Aachen

In [24]:
combined_df['Team'] = combined_df['Team'].replace("M'gladbach", "MGladbach")
combined_df['Team'] = combined_df['Team'].replace("Nott'm Forest", "Nottm Forest")

In [25]:
sorted_df = (combined_df.groupby(['Division','Season','Team']).agg(Sequence = ('Points', list)).reset_index())

sorted_df.rename(columns={'Division': 'League'}, inplace=True)

sorted_df['League'] = sorted_df['League'].replace("E0", "Premier_League")
sorted_df['League'] = sorted_df['League'].replace("D1", "Bundesliga")
sorted_df['League'] = sorted_df['League'].replace("SP1", "La_Liga")
sorted_df

,League,Season,Team,Sequence
0,Bundesliga,2000,Bayern Munich,"[3, 3, 3, 0, 3, 3, 0, 0, 3, 1, 3, 0, 0, 1, 3, ..."
1,Bundesliga,2000,Bochum,"[3, 0, 0, 0, 3, 1, 3, 0, 0, 0, 1, 0, 1, 0, 3, ..."
2,Bundesliga,2000,Cottbus,"[0, 0, 0, 3, 0, 0, 1, 3, 0, 3, 1, 3, 0, 0, 3, ..."
3,Bundesliga,2000,Dortmund,"[3, 3, 0, 3, 3, 0, 1, 3, 0, 0, 0, 3, 1, 3, 3, ..."
4,Bundesliga,2000,Ein Frankfurt,"[3, 0, 3, 0, 3, 1, 1, 0, 0, 3, 0, 3, 3, 0, 0, ..."
...,...,...,...,...
1428,La_Liga,2024,Sociedad,"[0, 3, 0, 1, 0, 0, 1, 3, 1, 3, 0, 3, 3, 0, 3, ..."
1429,La_Liga,2024,Valencia,"[0, 0, 0, 1, 0, 3, 1, 0, 1, 0, 1, 3, 0, 0, 0, ..."
1430,La_Liga,2024,Valladolid,"[3, 0, 1, 0, 0, 1, 0, 0, 0, 3, 0, 0, 1, 0, 0, ..."
1431,La_Liga,2024,Vallecano,"[3, 1, 0, 0, 3, 1, 1, 1, 3, 0, 3, 0, 0, 0, 3, ..."
1432,La_Liga,2024,Villarreal,"[1, 3, 3, 1, 3, 0, 3, 3, 0, 1, 3, 3, 1, 1, 0, ..."

In [26]:
#check if season length is good in sequences
sorted_df['seq_len'] = sorted_df['Sequence'].apply(len)
sorted_df[sorted_df['League'] == 'Bundesliga'].groupby('Season')['seq_len'].mean()

Season
2000    29.904762
2001    33.111111
2002    32.222222
2003    21.555556
2004    34.000000
2005    34.000000
2006    34.000000
2007    34.000000
2008    34.000000
2009    34.000000
2010    34.000000
2011    34.000000
2012    34.000000
2013    34.000000
2014    34.000000
2015    34.000000
2016    34.000000
2017    34.000000
2018    34.000000
2019    34.000000
2020    34.000000
2021    34.000000
2022    34.000000
2023    34.000000
2024    34.000000
Name: seq_len, dtype: float64

In [27]:
expected = {
    'Premier_League': 20,
    'Bundesliga': 18,
    'La_Liga': 20  # adjust as needed
}

counts = sorted_df.groupby(['League', 'Season'])['Team'].nunique()

# Filter to only rows that don't match expected
mask = counts.index.get_level_values('League').map(expected) != counts.values
counts[mask]

League      Season
Bundesliga  2000      21
Name: Team, dtype: int64

In [28]:
sorted_df = sorted_df[sorted_df['seq_len'] > 1]

In [29]:
sorted_df.to_csv('soccer.csv')

In [30]:
sorted_df.to_csv('../data/processed/soccer.csv')

# Creating a binary csv removing all draws

In [31]:
def winLossOnly(seq):
    result = []
    for x in seq:
        if x==3:
            result.append(1)
        elif x == 0:
            result.append(0)
    return result

In [32]:
dfWLO = sorted_df.copy()

In [33]:
dfWLO['Sequence']=dfWLO['Sequence'].apply(winLossOnly)
dfWLO.head()

,League,Season,Team,Sequence,seq_len
0,Bundesliga,2000,Bayern Munich,"[1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, ...",35
1,Bundesliga,2000,Bochum,"[1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, ...",34
2,Bundesliga,2000,Cottbus,"[0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, ...",35
3,Bundesliga,2000,Dortmund,"[1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, ...",35
4,Bundesliga,2000,Ein Frankfurt,"[1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, ...",34

In [34]:

dfWLO.head()

,League,Season,Team,Sequence,seq_len
0,Bundesliga,2000,Bayern Munich,"[1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, ...",35
1,Bundesliga,2000,Bochum,"[1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, ...",34
2,Bundesliga,2000,Cottbus,"[0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, ...",35
3,Bundesliga,2000,Dortmund,"[1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, ...",35
4,Bundesliga,2000,Ein Frankfurt,"[1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, ...",34

In [35]:
dfWLO.to_csv('soccer_binary.csv', index = False)

In [36]:
dfWLO['Sequence'].str.len()

0       29
1       28
2       32
3       25
4       29
        ..
1428    31
1429    25
1430    34
1431    25
1432    28
Name: Sequence, Length: 1430, dtype: int64

In [37]:
sorted_df.to_csv('../data/processed/soccer_binary.csv', index = False)