In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Matches.csv')

/var/folders/lt/f9thf0y579g40fr15z8xnfsc0000gn/T/ipykernel_10984/1234005553.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Matches.csv')

In [3]:
df.head()

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
0,F1,2000-07-28,NaN,Marseille,Troyes,1686.34,1586.57,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,2000-07-28,NaN,Paris SG,Strasbourg,1714.89,1642.51,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F2,2000-07-28,NaN,Wasquehal,Nancy,1465.08,1633.80,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,2000-07-29,NaN,Auxerre,Sedan,1635.58,1624.22,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,2000-07-29,NaN,Bordeaux,Metz,1734.34,1673.11,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df2 = df[['Division', 'MatchDate', 'HomeTeam', 'AwayTeam', 'FTResult']]
df2.head()

  Division   MatchDate   HomeTeam    AwayTeam FTResult
0       F1  2000-07-28  Marseille      Troyes        H
1       F1  2000-07-28   Paris SG  Strasbourg        H
2       F2  2000-07-28  Wasquehal       Nancy        A
3       F1  2000-07-29    Auxerre       Sedan        A
4       F1  2000-07-29   Bordeaux        Metz        D

In [9]:
df2.shape

(230557, 5)

In [11]:
df3 = df2[(df2['Division'] == 'E1') | (df2['Division'] == 'SP1') | (df2['Division'] == 'D1')]
df3.head()

   Division   MatchDate        HomeTeam       AwayTeam FTResult
39       D1  2000-08-11        Dortmund  Hansa Rostock        H
42       D1  2000-08-12   Bayern Munich         Hertha        H
43       D1  2000-08-12        Freiburg      Stuttgart        H
44       D1  2000-08-12         Hamburg    Munich 1860        D
45       D1  2000-08-12  Kaiserslautern         Bochum        A

In [13]:
df3.shape

(30136, 5)

In [15]:
df4 = df3.copy()
df4.head()

   Division   MatchDate        HomeTeam       AwayTeam FTResult
39       D1  2000-08-11        Dortmund  Hansa Rostock        H
42       D1  2000-08-12   Bayern Munich         Hertha        H
43       D1  2000-08-12        Freiburg      Stuttgart        H
44       D1  2000-08-12         Hamburg    Munich 1860        D
45       D1  2000-08-12  Kaiserslautern         Bochum        A

In [17]:
df4['MatchDate'] = pd.to_datetime(df4['MatchDate'])
df4.head()

   Division  MatchDate        HomeTeam       AwayTeam FTResult
39       D1 2000-08-11        Dortmund  Hansa Rostock        H
42       D1 2000-08-12   Bayern Munich         Hertha        H
43       D1 2000-08-12        Freiburg      Stuttgart        H
44       D1 2000-08-12         Hamburg    Munich 1860        D
45       D1 2000-08-12  Kaiserslautern         Bochum        A

In [19]:
df4['Season'] = df4['Season'] = np.where(df4['MatchDate'].dt.month >=7,
                                        df4['MatchDate'].dt.year,
                                        df4['MatchDate'].dt.year -1)
df4

       Division  MatchDate        HomeTeam       AwayTeam FTResult  Season
39           D1 2000-08-11        Dortmund  Hansa Rostock        H    2000
42           D1 2000-08-12   Bayern Munich         Hertha        H    2000
43           D1 2000-08-12        Freiburg      Stuttgart        H    2000
44           D1 2000-08-12         Hamburg    Munich 1860        D    2000
45           D1 2000-08-12  Kaiserslautern         Bochum        A    2000
...         ...        ...             ...            ...      ...     ...
230497      SP1 2025-05-24          Getafe          Celta        A    2024
230498      SP1 2025-05-24       Vallecano       Mallorca        D    2024
230499      SP1 2025-05-25          Girona     Ath Madrid        A    2024
230500      SP1 2025-05-25      Villarreal        Sevilla        H    2024
230535      SP1 2025-05-25      Ath Bilbao      Barcelona        A    2024

[30136 rows x 6 columns]

In [21]:
home_df = df4[['Division', 'MatchDate', 'HomeTeam', 'FTResult', 'Season']]
home_df

       Division  MatchDate        HomeTeam FTResult  Season
39           D1 2000-08-11        Dortmund        H    2000
42           D1 2000-08-12   Bayern Munich        H    2000
43           D1 2000-08-12        Freiburg        H    2000
44           D1 2000-08-12         Hamburg        D    2000
45           D1 2000-08-12  Kaiserslautern        A    2000
...         ...        ...             ...      ...     ...
230497      SP1 2025-05-24          Getafe        A    2024
230498      SP1 2025-05-24       Vallecano        D    2024
230499      SP1 2025-05-25          Girona        A    2024
230500      SP1 2025-05-25      Villarreal        H    2024
230535      SP1 2025-05-25      Ath Bilbao        A    2024

[30136 rows x 5 columns]

In [23]:
def points(result):
    if result == 'H':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

In [25]:
home_df['Points'] = home_df['FTResult'].apply(points)

In [27]:
home_df

       Division  MatchDate        HomeTeam FTResult  Season  Points
39           D1 2000-08-11        Dortmund        H    2000       3
42           D1 2000-08-12   Bayern Munich        H    2000       3
43           D1 2000-08-12        Freiburg        H    2000       3
44           D1 2000-08-12         Hamburg        D    2000       1
45           D1 2000-08-12  Kaiserslautern        A    2000       0
...         ...        ...             ...      ...     ...     ...
230497      SP1 2025-05-24          Getafe        A    2024       0
230498      SP1 2025-05-24       Vallecano        D    2024       1
230499      SP1 2025-05-25          Girona        A    2024       0
230500      SP1 2025-05-25      Villarreal        H    2024       3
230535      SP1 2025-05-25      Ath Bilbao        A    2024       0

[30136 rows x 6 columns]

In [29]:
home_df['Team'] = home_df['HomeTeam']
home_df.head()

,Division,MatchDate,HomeTeam,FTResult,Season,Points,Team
39,D1,2000-08-11,Dortmund,H,2000,3,Dortmund
42,D1,2000-08-12,Bayern Munich,H,2000,3,Bayern Munich
43,D1,2000-08-12,Freiburg,H,2000,3,Freiburg
44,D1,2000-08-12,Hamburg,D,2000,1,Hamburg
45,D1,2000-08-12,Kaiserslautern,A,2000,0,Kaiserslautern

In [31]:
def away_points(result):
    if result == 'A':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

In [33]:
away_df = df4[['Division', 'MatchDate', 'AwayTeam', 'FTResult', 'Season']]
away_df

       Division  MatchDate       AwayTeam FTResult  Season
39           D1 2000-08-11  Hansa Rostock        H    2000
42           D1 2000-08-12         Hertha        H    2000
43           D1 2000-08-12      Stuttgart        H    2000
44           D1 2000-08-12    Munich 1860        D    2000
45           D1 2000-08-12         Bochum        A    2000
...         ...        ...            ...      ...     ...
230497      SP1 2025-05-24          Celta        A    2024
230498      SP1 2025-05-24       Mallorca        D    2024
230499      SP1 2025-05-25     Ath Madrid        A    2024
230500      SP1 2025-05-25        Sevilla        H    2024
230535      SP1 2025-05-25      Barcelona        A    2024

[30136 rows x 5 columns]

In [35]:
away_df['Points'] = away_df['FTResult'].apply(away_points)

In [37]:
away_df

       Division  MatchDate       AwayTeam FTResult  Season  Points
39           D1 2000-08-11  Hansa Rostock        H    2000       0
42           D1 2000-08-12         Hertha        H    2000       0
43           D1 2000-08-12      Stuttgart        H    2000       0
44           D1 2000-08-12    Munich 1860        D    2000       1
45           D1 2000-08-12         Bochum        A    2000       3
...         ...        ...            ...      ...     ...     ...
230497      SP1 2025-05-24          Celta        A    2024       3
230498      SP1 2025-05-24       Mallorca        D    2024       1
230499      SP1 2025-05-25     Ath Madrid        A    2024       3
230500      SP1 2025-05-25        Sevilla        H    2024       0
230535      SP1 2025-05-25      Barcelona        A    2024       3

[30136 rows x 6 columns]

In [39]:
away_df['Team'] = away_df['AwayTeam']
away_df.head()

   Division  MatchDate       AwayTeam FTResult  Season  Points           Team
39       D1 2000-08-11  Hansa Rostock        H    2000       0  Hansa Rostock
42       D1 2000-08-12         Hertha        H    2000       0         Hertha
43       D1 2000-08-12      Stuttgart        H    2000       0      Stuttgart
44       D1 2000-08-12    Munich 1860        D    2000       1    Munich 1860
45       D1 2000-08-12         Bochum        A    2000       3         Bochum

In [41]:
combined_df = pd.concat([home_df, away_df], ignore_index = True)
combined_df

,Division,MatchDate,HomeTeam,FTResult,Season,Points,Team,AwayTeam
0,D1,2000-08-11,Dortmund,H,2000,3,Dortmund,NaN
1,D1,2000-08-12,Bayern Munich,H,2000,3,Bayern Munich,NaN
2,D1,2000-08-12,Freiburg,H,2000,3,Freiburg,NaN
3,D1,2000-08-12,Hamburg,D,2000,1,Hamburg,NaN
4,D1,2000-08-12,Kaiserslautern,A,2000,0,Kaiserslautern,NaN
...,...,...,...,...,...,...,...,...
60267,SP1,2025-05-24,NaN,A,2024,3,Celta,Celta
60268,SP1,2025-05-24,NaN,D,2024,1,Mallorca,Mallorca
60269,SP1,2025-05-25,NaN,A,2024,3,Ath Madrid,Ath Madrid
60270,SP1,2025-05-25,NaN,H,2024,0,Sevilla,Sevilla
60271,SP1,2025-05-25,NaN,A,2024,3,Barcelona,Barcelona

In [43]:
combined_df = combined_df.sort_values(['Division', 'Team', 'Season', 'MatchDate'])
combined_df.head()

      Division  MatchDate HomeTeam FTResult  Season  Points    Team AwayTeam
37159       D1 2006-08-12      NaN        H    2006       0  Aachen   Aachen
7043        D1 2006-08-19   Aachen        A    2006       0  Aachen      NaN
37202       D1 2006-08-26      NaN        A    2006       3  Aachen   Aachen
7109        D1 2006-09-16   Aachen        H    2006       3  Aachen      NaN
37266       D1 2006-09-23      NaN        H    2006       0  Aachen   Aachen

In [45]:
sorted_df = (combined_df.groupby(['Division','Season','Team']).agg(Sequence = ('Points', list)).reset_index())
sorted_df

,Division,Season,Team,Sequence
0,D1,2000,Bayern Munich,"[3, 3, 3, 0, 3, 3, 0, 0, 3, 1, 3, 0, 0, 1, 3, ..."
1,D1,2000,Bochum,"[3, 0, 0, 0, 3, 1, 3, 0, 0, 0, 1, 0, 1, 0, 3, ..."
2,D1,2000,Cottbus,"[0, 0, 0, 3, 0, 0, 1, 3, 0, 3, 1, 3, 0, 0, 3, ..."
3,D1,2000,Dortmund,"[3, 3, 0, 3, 3, 0, 1, 3, 0, 0, 0, 3, 1, 3, 3, ..."
4,D1,2000,Ein Frankfurt,"[3, 0, 3, 0, 3, 1, 1, 0, 0, 3, 0, 3, 3, 0, 0, ..."
...,...,...,...,...
1535,SP1,2024,Sociedad,"[0, 3, 0, 1, 0, 0, 1, 3, 1, 3, 0, 3, 3, 0, 3, ..."
1536,SP1,2024,Valencia,"[0, 0, 0, 1, 0, 3, 1, 0, 1, 0, 1, 3, 0, 0, 0, ..."
1537,SP1,2024,Valladolid,"[3, 0, 1, 0, 0, 1, 0, 0, 0, 3, 0, 0, 1, 0, 0, ..."
1538,SP1,2024,Vallecano,"[3, 1, 0, 0, 3, 1, 1, 1, 3, 0, 3, 0, 0, 0, 3, ..."
1539,SP1,2024,Villarreal,"[1, 3, 3, 1, 3, 0, 3, 3, 0, 1, 3, 3, 1, 1, 0, ..."

In [65]:
sorted_df.to_csv('soccer.csv')

In [61]:
sorted_df['Team'].unique()

array(['Bayern Munich', 'Bochum', 'Cottbus', 'Dortmund', 'Ein Frankfurt',
       'FC Koln', 'Freiburg', 'Hamburg', 'Hansa Rostock', 'Hertha',
       'Kaiserslautern', 'Leverkusen', 'Munich 1860', 'Schalke 04',
       'Stuttgart', 'Unterhaching', 'Werder Bremen', 'Wolfsburg',
       'MGladbach', 'Nurnberg', 'St Pauli', 'Bielefeld', 'Hannover',
       'Mainz', 'Duisburg', 'Aachen', 'Karlsruhe', 'Hoffenheim',
       'Augsburg', 'Fortuna Dusseldorf', 'Greuther Furth', 'Braunschweig',
       'Paderborn', 'Darmstadt', 'Ingolstadt', 'RB Leipzig',
       'Union Berlin', 'Heidenheim', 'Holstein Kiel', "M'gladbach",
       'Barnsley', 'Birmingham', 'Blackburn', 'Bolton', 'Burnley',
       'Crewe', 'Crystal Palace', 'Fulham', 'Gillingham', 'Grimsby',
       'Huddersfield', 'Norwich', 'Nottm Forest', 'Portsmouth', 'Preston',
       'QPR', 'Sheffield United', 'Sheffield Weds', 'Stockport',
       'Tranmere', 'Watford', 'West Brom', 'Wimbledon', 'Wolves',
       'Bradford', 'Coventry', 'Man City', 'Millwall', 'Rotherham',
       'Walsall', 'Brighton', 'Derby', 'Ipswich', 'Leicester', 'Reading',
       'Stoke', 'Cardiff', 'Sunderland', 'West Ham', 'Wigan', 'Leeds',
       'Plymouth', 'Hull', 'Luton', 'Southampton', 'Colchester',
       'Southend', 'Blackpool', 'Bristol City', 'Charlton', 'Scunthorpe',
       'Doncaster', 'Swansea', 'Middlesbrough', 'Newcastle', 'Peterboro',
       'Bournemouth', 'Yeovil', 'Brentford', 'Milton Keynes Dons',
       'Aston Villa', 'Burton', 'Wycombe', 'Oxford', 'Alaves',
       'Ath Bilbao', 'Barcelona', 'Celta', 'Espanol', 'La Coruna',
       'Las Palmas', 'Malaga', 'Mallorca', 'Numancia', 'Osasuna',
       'Oviedo', 'Real Madrid', 'Santander', 'Sociedad', 'Valencia',
       'Valladolid', 'Vallecano', 'Villarreal', 'Zaragoza', 'Betis',
       'Sevilla', 'Tenerife', 'Ath Madrid', 'Recreativo', 'Albacete',
       'Murcia', 'Getafe', 'Levante', 'Cadiz', 'Almeria', 'Sp Gijon',
       'Xerez', 'Hercules', 'Granada', 'Elche', 'Cordoba', 'Eibar',
       'Leganes', 'Girona', 'Huesca'], dtype=object)